import 'activities.dart';

Map<Activities, String> sportsTranslation = {
  Activities.RUNNING: 'Course à pied',
  Activities.CYCLING: 'Cyclisme',
  Activities.SWIMMING: 'Natation',
  Activities.WEIGHTLIFTING: 'Musculation',
  Activities.YOGA: 'Yoga',
  Activities.PILATES: 'Pilates',
  Activities.MARTIAL_ARTS: 'Arts martiaux',
  Activities.DANCING: 'Danse',
  Activities.HIKING: 'Randonnée',
  Activities.ROCK_CLIMBING: 'Escalade',
  Activities.TENNIS: 'Tennis',
  Activities.BASKETBALL: 'Basketball',
  Activities.SOCCER: 'Football',
  Activities.VOLLEYBALL: 'Volleyball',
  Activities.BASEBALL: 'Baseball',
  Activities.SKIING: 'Ski',
  Activities.SNOWBOARDING: 'Snowboard',
  Activities.SURFING: 'Surf',
  Activities.GOLF: 'Golf',
  Activities.ROWING: 'Aviron',
  Activities.CROSSFIT: 'Crossfit',
  Activities.GYMNASTICS: 'Gymnastique',
  Activities.TRIATHLON: 'Triathlon',
  Activities.RUGBY: 'Rugby',
  Activities.BOXING: 'Boxe',
  Activities.SKATING: 'Patinage',
  Activities.SQUASH: 'Squash',
  Activities.BADMINTON: 'Badminton',
  Activities.HORSE_RIDING: 'Équitation',
  Activities.TABLE_TENNIS: 'Tennis de table',
};

Map<Activities, String> activitiesIconsMap = {
  Activities.RUNNING: 'assets/images/running.png',
  Activities.CYCLING: 'assets/images/cycling.png',
  Activities.SWIMMING: 'assets/images/swimming.png',
  Activities.WEIGHTLIFTING: 'assets/images/weightlifting.png',
  Activities.YOGA: 'assets/images/yoga.png',
  Activities.PILATES: 'assets/images/a0.png',
  Activities.MARTIAL_ARTS: 'assets/images/martial-art.png',
  Activities.DANCING: 'assets/images/dancing.png',
  Activities.HIKING: 'assets/images/hiking.png',
  Activities.ROCK_CLIMBING: 'assets/images/rock-climbing.png',
  Activities.TENNIS: 'assets/images/tennis.png',
  Activities.BASKETBALL: 'assets/images/basketball.png',
  Activities.SOCCER: 'assets/images/soccer.png',
  Activities.VOLLEYBALL: 'assets/images/volleyball.png',
  Activities.BASEBALL: 'assets/images/baseball.png',
  Activities.SKIING: 'assets/images/skiing.png',
  Activities.SNOWBOARDING: 'assets/images/snowboarding.png',
  Activities.SURFING: 'assets/images/surfing.png',
  Activities.GOLF: 'assets/images/golf.png',
  Activities.ROWING: 'assets/images/rowing.png',
  Activities.CROSSFIT: 'assets/images/crossfit.png',
  Activities.GYMNASTICS: 'assets/images/gymnastics.png',
  Activities.TRIATHLON: 'assets/images/a0.png',
  Activities.RUGBY: 'assets/images/rugby.png',
  Activities.BOXING: 'assets/images/boxing.png',
  Activities.SKATING: 'assets/images/skating.png',
  Activities.SQUASH: 'assets/images/a0.png',
  Activities.BADMINTON: 'assets/images/badminton.png',
  Activities.HORSE_RIDING: 'assets/images/horse-riding.png',
  Activities.TABLE_TENNIS: 'assets/images/table-tennis.png',
};
