import 'activities.dart';

Map<Activities, String> sportsTranslation = {
  Activities.RUNNING: 'Course à pied',
  Activities.CYCLING: 'Cyclisme',
  Activities.SWIMMING: 'Natation',
  Activities.WEIGHTLIFTING: 'Musculation',
  Activities.YOGA: 'Yoga',
  Activities.PILATES: 'Pilates',
  Activities.MARTIAL_ARTS: 'Arts martiaux',
  Activities.DANCING: 'Danse',
  Activities.HIKING: 'Randonnée',
  Activities.ROCK_CLIMBING: 'Escalade',
  Activities.TENNIS: 'Tennis',
  Activities.BASKETBALL: 'Basketball',
  Activities.SOCCER: 'Football',
  Activities.VOLLEYBALL: 'Volleyball',
  Activities.BASEBALL: 'Baseball',
  Activities.SKIING: 'Ski',
  Activities.SNOWBOARDING: 'Snowboard',
  Activities.SURFING: 'Surf',
  Activities.GOLF: 'Golf',
  Activities.ROWING: 'Aviron',
  Activities.CROSSFIT: 'Crossfit',
  Activities.GYMNASTICS: 'Gymnastique',
  Activities.TRIATHLON: 'Triathlon',
  Activities.RUGBY: 'Rugby',
  Activities.BOXING: 'Boxe',
  Activities.SKATING: 'Patinage',
  Activities.SQUASH: 'Squash',
  Activities.BADMINTON: 'Badminton',
  Activities.HORSE_RIDING: 'Équitation',
  Activities.TABLE_TENNIS: 'Tennis de table',
};
